version: '3.0'

services:
  db:
    env_file: env/default
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    env_file: env/default
    image: redis
    ports:
      - "6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./gtfs:/usr/share/nginx/html

  app:
    env_file: env/default
    build: .
    command: bash ./wait-for-it.sh -h db -p 5432 -- bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - nginx

  sidekiq:
    env_file: env/default
    build: .
    command: bash ./wait-for-it.sh -h db -p 5432 -- bundle exec sidekiq
    volumes:
      - ".:/app"
    depends_on:
      - nginx
      - redis
      - db
